### ISSUE TITLE
Нарушение лицензии 

### ISSUE THREAD

**Issue by flexagoon** [FoxFil/foxfil#1]
Здравствуйте, мы обнаружили, что данный репозиторий содержит в себе контент, скопированный из двух других репозиториев:

https://github.com/flexagoon/flexagoon
https://github.com/Ultrageopro1966/Ultrageopro1966

Обращаем ваше внимание на то, что вышеуказанные репозитории не содержат файла LICENSE, а значит, по умолчанию, являются интеллектуальной собственностью их владельцев.

Просим вас удалить незаконно использованный контент из вашего репозитория.

**Comment by FoxFil** [comment]
паш иди в попку

**Comment by Ultrageopro1966** [comment]
Здравствуйте, спасибо что обратили внимание. Действительно, владелец аккаунта foxfil незаконно использовал конетент из нашего README файла [репозиторий](https://github.com/Ultrageopro1966/Ultrageopro1966) (блоки со статистикой аккаунта GitHub), нарушив право на интеллектуальную собственность.

Заметим, что данный репозиторий не защищён лицензией, потому копирование и дальнейшая публикация контента, в нем представленного, незаконна. 

Просим удалить весь скопированный контент.
